name: github_repo_viewer
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  auto_route: ^3.2.1
  cached_network_image: ^3.2.0
  dartz: ^0.10.1
  dio: ^5.1.2
  flash: ^2.0.3+2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_riverpod: ^1.0.3
  flutter_secure_storage: ^5.0.2
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  material_design_icons_flutter: ^5.0.6595
  material_floating_search_bar: ^0.3.6
  oauth2: ^2.0.0
  path_provider: ^2.0.8
  path: ^1.8.1
  sembast: ^3.1.1+1
  shimmer: ^2.0.0
  webview_flutter: ^3.0.0
  url_launcher: ^6.0.18
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  flutter_markdown: ^0.6.2
  sqflite: ^2.0.0+4
  
dev_dependencies:
  auto_route_generator: ^3.2.1
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  freezed: ^1.1.1
  json_serializable: ^6.1.4
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/.env

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
